name: "infra-preview-deploy"

on:
  push:
    branches:
      - main
    paths:
      - 10_infra/**
      - .github/workflows/**
      - 30_app/**
  workflow_dispatch:

jobs:
  preview:
    name: "Preview"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./30_app
        run: npm install

      - name: Run Lint (via npm script)
        working-directory: ./30_app
        run: npm run lint || true

      - name: Upload ESLint summary report
        uses: actions/upload-artifact@v4
        with:
          name: eslint-summary
          path: ./30_app/output/test/lint-summary.txt

      - name: Upload ESLint HTML report
        uses: actions/upload-artifact@v4
        with:
          name: eslint-html
          path: ./30_app/output/test/lint-results.html

      - name: Upload ESLint JUnit report
        uses: actions/upload-artifact@v4
        with:
          name: eslint-junit
          path: ./30_app/output/test/lint-results.xml